<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>DapperMany.MySql</AssemblyName>
    <RootNamespace>DapperMany.MySql</RootNamespace>
    <PackageId>DMany.MySql</PackageId>
    <Summary>MySQL provider for DapperMany</Summary>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <DocumentationFile>bin\$(Configuration)\$(TargetFramework)\$(AssemblyName).xml</DocumentationFile>
    <PackageIcon>mark.png</PackageIcon>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\assets\mark.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../DapperMany/DapperMany.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MySqlConnector" Version="2.2.0" />
  </ItemGroup>

</Project>
