namespace DapperMany.Attributes;

using System;

/// <summary>
/// Specifies how a property value is generated (e.g., Identity auto-increment).
/// Reuses System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedAttribute for compatibility.
/// </summary>
[AttributeUsage(AttributeTargets.Property, AllowMultiple = false)]
public class DatabaseGeneratedAttribute : Attribute
{
    /// <summary>
    /// The generation strategy for the property.
    /// </summary>
    public DatabaseGeneratedOption Option { get; }

    /// <summary>
    /// Initializes a new instance of the DatabaseGeneratedAttribute class.
    /// </summary>
    /// <param name="option">The database generation option.</param>
    public DatabaseGeneratedAttribute(DatabaseGeneratedOption option)
    {
        Option = option;
    }
}

/// <summary>
/// Specifies database generation options for properties.
/// </summary>
public enum DatabaseGeneratedOption
{
    /// <summary>
    /// The property value is not generated by the database.
    /// </summary>
    None = 0,

    /// <summary>
    /// The property value is generated by the database as an identity column (auto-increment).
    /// </summary>
    Identity = 1,

    /// <summary>
    /// The property value is generated by the database on each insert or update.
    /// </summary>
    Computed = 2
}
