namespace DapperMany.Samples.Models;

/// <summary>
/// ItemPedido (Order Item) entity representing a line item in a purchase order.
/// Maps to the dbo.ItensPedido table in the database.
/// </summary>
[System.ComponentModel.DataAnnotations.Schema.Table("ItensPedido")]
public class ItemPedido
{
    /// <summary>
    /// Unique identifier for the order item (Primary Key).
    /// Auto-generated by the database.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Key]
    [System.ComponentModel.DataAnnotations.Schema.DatabaseGenerated(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity)]
    public int Id { get; set; }

    /// <summary>
    /// Foreign key referencing the parent Pedido.
    /// </summary>
    public int PedidoId { get; set; }

    /// <summary>
    /// Description of the item (e.g., product name, SKU).
    /// </summary>
    public required string Descricao { get; set; }

    /// <summary>
    /// Quantity of items ordered.
    /// </summary>
    public int Quantidade { get; set; } = 1;

    /// <summary>
    /// Unit price of the item.
    /// </summary>
    public decimal ValorUnitario { get; set; }

    /// <summary>
    /// Total price for this line item (Quantidade × ValorUnitario).
    /// </summary>
    public decimal ValorTotal { get; set; }

    /// <summary>
    /// Timestamp when the item was created.
    /// </summary>
    public DateTime Created { get; set; } = DateTime.UtcNow;

    /// <summary>
    /// Timestamp when the item was last modified.
    /// </summary>
    public DateTime Modified { get; set; } = DateTime.UtcNow;
}
