using DapperMany.Attributes;

namespace DapperMany.Samples.Models;

/// <summary>
/// Pedido (Order) entity representing a customer purchase order.
/// Maps to the dbo.Pedidos table in the database.
/// </summary>
[System.ComponentModel.DataAnnotations.Schema.Table("Pedidos")]
public class Pedido
{
    /// <summary>
    /// Unique identifier for the order (Primary Key).
    /// Auto-generated by the database.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Key]
    [System.ComponentModel.DataAnnotations.Schema.DatabaseGenerated(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity)]
    public int Id { get; set; }

    /// <summary>
    /// Order document number (e.g., invoice number, PO number).
    /// Must be unique across all orders.
    /// </summary>
    public required string NumeroDocumento { get; set; }

    /// <summary>
    /// Date when the order was placed.
    /// </summary>
    public DateTime DataPedido { get; set; } = DateTime.UtcNow;

    /// <summary>
    /// Total value of the order (sum of all items).
    /// </summary>
    public decimal ValorTotal { get; set; }

    /// <summary>
    /// Status of the order (e.g., "Pendente", "Processado", "Cancelado").
    /// </summary>
    public string Status { get; set; } = "Pendente";

    /// <summary>
    /// Timestamp when the order was created.
    /// </summary>
    public DateTime Created { get; set; } = DateTime.UtcNow;

    /// <summary>
    /// Timestamp when the order was last modified.
    /// </summary>
    public DateTime Modified { get; set; } = DateTime.UtcNow;

    /// <summary>
    /// Order line items (one-to-many relationship).
    /// Used with [HasMany] attribute for graph inserts.
    /// FK will be auto-populated during InsertManyGraph operation.
    /// </summary>
    [HasMany(nameof(ItemPedido.PedidoId))]
    public List<ItemPedido> Itens { get; set; } = new();
}
